# Generated by Django 4.1.3 on 2023-03-26 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_squashed_0010_rename_is_part_host_registration_is_party_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Internal Key')),
                ('name', models.CharField(max_length=20, verbose_name='Table Name')),
                ('order', models.IntegerField(default=0, verbose_name='Order to display')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Table Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('wares_description', models.TextField(verbose_name='Description of Wares')),
                ('helper_legal_name', models.CharField(blank=True, max_length=200)),
                ('helper_fan_name', models.CharField(blank=True, max_length=200)),
                ('special_requests', models.TextField(blank=True)),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('table_assigned', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.event')),
                ('table_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
