# Generated by Django 4.1.3 on 2023-03-25 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_membership_included_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(verbose_name='I am bringing child')),
                ('is_merchant', models.BooleanField(verbose_name='I am planning to be a Merchant')),
                ('is_part_host', models.BooleanField(verbose_name='I am planning to host a party')),
                ('is_volunteer', models.BooleanField(verbose_name='I want to volunteer')),
                ('is_paid', models.BooleanField(verbose_name='Registration is paid')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.event')),
                ('membership', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shared.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
