# Generated by Django 4.1.3 on 2023-03-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_alter_registration_is_merchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.membership'),
        ),
    ]
