# Generated by Django 4.1.3 on 2023-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_alter_registration_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='user_selection_required',
            field=models.BooleanField(default=False),
        ),
    ]
