# Generated by Django 4.1.3 on 2023-03-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_registrationproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationproduct',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.producttypeattribute'),
        ),
    ]
