# Generated by Django 4.1.3 on 2023-03-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_alter_registrationproduct_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationproduct',
            name='attribute',
            field=models.TextField(default='', verbose_name='Attribute Value'),
        ),
    ]
