# Generated by Django 4.1.3 on 2023-03-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_alter_registrationproduct_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='is_part_host',
            new_name='is_party_host',
        ),
    ]
