# Generated by Django 4.1.7 on 2023-04-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_squashed_0010_rename_is_part_host_registration_is_party_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_merchant',
            field=models.BooleanField(default=False, verbose_name='Available to Merchants'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_parent',
            field=models.BooleanField(default=False, verbose_name='Available to Parents'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_at_event',
            field=models.BooleanField(default=True, verbose_name='At Event Availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_pre_event',
            field=models.BooleanField(default=True, verbose_name='Pre Event Availability'),
        ),
    ]
