# Generated by Django 4.1.7 on 2023-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_product_available_merchant_product_available_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='available_merchants',
            field=models.BooleanField(default=False, verbose_name='Available to Merchants'),
        ),
        migrations.AddField(
            model_name='membership',
            name='available_parents',
            field=models.BooleanField(default=False, verbose_name='Available to Parents'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='available_at_event',
            field=models.BooleanField(default=True, verbose_name='At Event Availability'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='available_pre_event',
            field=models.BooleanField(default=True, verbose_name='Pre Event Availability'),
        ),
    ]
