from .console_index import ConsoleIndexPageView
from .events_list import EventsListPageView
from .events_create import EventsCreatePageView
from .events_detail import EventsDetailsPageView
from .memberships_create import MembershipsCreatePageView
from .memberships_detail import MembershipsDetailPageView
from .product_create import ProductCreatePageView
from .product_details import ProductDetailPageView